/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label;
    QLabel *status;
    QTextEdit *serial_output_tedit;
    QPushButton *test_button;
    QPushButton *test_button_2;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout;
    QComboBox *serial_interface_combo;
    QPushButton *serial_search_button;
    QPushButton *serial_open_button;
    QPushButton *serial_close_button;
    QPushButton *serial_clear_output_button;
    QPushButton *count_reset_button;
    QPushButton *reorder_button;
    QPushButton *serial_send_button;
    QPlainTextEdit *serial_command_tedit;
    QPushButton *clear_warning_button;
    QLabel *label_2;
    QPushButton *test_button_3;
    QSplitter *splitter;
    QSplitter *container_RSU_1;
    QLabel *label_RSU_1;
    QLCDNumber *temp_display_1;
    QLCDNumber *batt_display_1;
    QSplitter *splitter_1;
    QProgressBar *temp_pb_1;
    QProgressBar *batt_pb_1;
    QSplitter *container_RSU_2;
    QLabel *label_RSU_2;
    QLCDNumber *temp_display_2;
    QLCDNumber *batt_display_2;
    QSplitter *splitter_2;
    QProgressBar *temp_pb_2;
    QProgressBar *batt_pb_2;
    QSplitter *container_RSU_3;
    QLabel *label_RSU_3;
    QLCDNumber *temp_display_3;
    QLCDNumber *batt_display_3;
    QSplitter *splitter_3;
    QProgressBar *temp_pb_3;
    QProgressBar *batt_pb_3;
    QSplitter *container_RSU_4;
    QLabel *label_RSU_4;
    QLCDNumber *temp_display_4;
    QLCDNumber *batt_display_4;
    QSplitter *splitter_4;
    QProgressBar *temp_pb_4;
    QProgressBar *batt_pb_4;
    QSplitter *container_RSU_5;
    QLabel *label_RSU_5;
    QLCDNumber *temp_display_5;
    QLCDNumber *batt_display_5;
    QSplitter *splitter_5;
    QProgressBar *temp_pb_5;
    QProgressBar *batt_pb_5;
    QSplitter *container_RSU_6;
    QLabel *label_RSU_6;
    QLCDNumber *temp_display_6;
    QLCDNumber *batt_display_6;
    QSplitter *splitter_6;
    QProgressBar *temp_pb_6;
    QProgressBar *batt_pb_6;
    QSplitter *container_RSU_7;
    QLabel *label_RSU_7;
    QLCDNumber *temp_display_7;
    QLCDNumber *batt_display_7;
    QSplitter *splitter_7;
    QProgressBar *temp_pb_7;
    QProgressBar *batt_pb_7;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QComboBox *MU_message_cb;
    QPushButton *serial_MUsend_button;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *MU_message_response_lb;
    QSplitter *splitter_8;
    QLabel *label_8;
    QComboBox *power_cb;
    QPushButton *power_button;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QSpinBox *sector_RSU_sp_1;
    QSpinBox *sector_RSU_sp_2;
    QSpinBox *sector_RSU_sp_3;
    QSpinBox *sector_RSU_sp_4;
    QSpinBox *sector_RSU_sp_5;
    QSpinBox *sector_RSU_sp_6;
    QSpinBox *sector_RSU_sp_7;
    QSpinBox *sector_RSU_sp_8;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1130, 781);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(650, 20, 34, 17));
        status = new QLabel(centralWidget);
        status->setObjectName(QString::fromUtf8("status"));
        status->setGeometry(QRect(10, 430, 311, 17));
        serial_output_tedit = new QTextEdit(centralWidget);
        serial_output_tedit->setObjectName(QString::fromUtf8("serial_output_tedit"));
        serial_output_tedit->setGeometry(QRect(570, 40, 551, 361));
        test_button = new QPushButton(centralWidget);
        test_button->setObjectName(QString::fromUtf8("test_button"));
        test_button->setGeometry(QRect(990, 630, 89, 31));
        test_button_2 = new QPushButton(centralWidget);
        test_button_2->setObjectName(QString::fromUtf8("test_button_2"));
        test_button_2->setGeometry(QRect(990, 670, 89, 31));
        layoutWidget = new QWidget(centralWidget);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(690, 10, 432, 27));
        horizontalLayout = new QHBoxLayout(layoutWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        serial_interface_combo = new QComboBox(layoutWidget);
        serial_interface_combo->setObjectName(QString::fromUtf8("serial_interface_combo"));

        horizontalLayout->addWidget(serial_interface_combo);

        serial_search_button = new QPushButton(layoutWidget);
        serial_search_button->setObjectName(QString::fromUtf8("serial_search_button"));

        horizontalLayout->addWidget(serial_search_button);

        serial_open_button = new QPushButton(layoutWidget);
        serial_open_button->setObjectName(QString::fromUtf8("serial_open_button"));

        horizontalLayout->addWidget(serial_open_button);

        serial_close_button = new QPushButton(layoutWidget);
        serial_close_button->setObjectName(QString::fromUtf8("serial_close_button"));
        serial_close_button->setEnabled(false);

        horizontalLayout->addWidget(serial_close_button);

        serial_clear_output_button = new QPushButton(layoutWidget);
        serial_clear_output_button->setObjectName(QString::fromUtf8("serial_clear_output_button"));
        serial_clear_output_button->setEnabled(true);
        QFont font;
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        serial_clear_output_button->setFont(font);

        horizontalLayout->addWidget(serial_clear_output_button);

        count_reset_button = new QPushButton(centralWidget);
        count_reset_button->setObjectName(QString::fromUtf8("count_reset_button"));
        count_reset_button->setGeometry(QRect(20, 470, 101, 41));
        reorder_button = new QPushButton(centralWidget);
        reorder_button->setObjectName(QString::fromUtf8("reorder_button"));
        reorder_button->setGeometry(QRect(20, 518, 101, 41));
        serial_send_button = new QPushButton(centralWidget);
        serial_send_button->setObjectName(QString::fromUtf8("serial_send_button"));
        serial_send_button->setEnabled(false);
        serial_send_button->setGeometry(QRect(230, 400, 89, 30));
        serial_command_tedit = new QPlainTextEdit(centralWidget);
        serial_command_tedit->setObjectName(QString::fromUtf8("serial_command_tedit"));
        serial_command_tedit->setEnabled(false);
        serial_command_tedit->setGeometry(QRect(10, 400, 211, 30));
        clear_warning_button = new QPushButton(centralWidget);
        clear_warning_button->setObjectName(QString::fromUtf8("clear_warning_button"));
        clear_warning_button->setEnabled(true);
        clear_warning_button->setGeometry(QRect(430, 360, 111, 21));
        QFont font1;
        font1.setPointSize(12);
        font1.setBold(true);
        font1.setWeight(75);
        clear_warning_button->setFont(font1);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(420, 20, 141, 20));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        label_2->setFont(font2);
        test_button_3 = new QPushButton(centralWidget);
        test_button_3->setObjectName(QString::fromUtf8("test_button_3"));
        test_button_3->setGeometry(QRect(990, 710, 89, 31));
        splitter = new QSplitter(centralWidget);
        splitter->setObjectName(QString::fromUtf8("splitter"));
        splitter->setGeometry(QRect(160, 590, 512, 158));
        splitter->setOrientation(Qt::Horizontal);
        container_RSU_1 = new QSplitter(splitter);
        container_RSU_1->setObjectName(QString::fromUtf8("container_RSU_1"));
        container_RSU_1->setOrientation(Qt::Vertical);
        label_RSU_1 = new QLabel(container_RSU_1);
        label_RSU_1->setObjectName(QString::fromUtf8("label_RSU_1"));
        label_RSU_1->setFont(font2);
        label_RSU_1->setAlignment(Qt::AlignCenter);
        label_RSU_1->setWordWrap(false);
        container_RSU_1->addWidget(label_RSU_1);
        temp_display_1 = new QLCDNumber(container_RSU_1);
        temp_display_1->setObjectName(QString::fromUtf8("temp_display_1"));
        temp_display_1->setEnabled(false);
        temp_display_1->setFrameShape(QFrame::Box);
        temp_display_1->setFrameShadow(QFrame::Plain);
        temp_display_1->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_1->addWidget(temp_display_1);
        batt_display_1 = new QLCDNumber(container_RSU_1);
        batt_display_1->setObjectName(QString::fromUtf8("batt_display_1"));
        batt_display_1->setEnabled(false);
        batt_display_1->setFrameShape(QFrame::Box);
        batt_display_1->setFrameShadow(QFrame::Plain);
        batt_display_1->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_1->addWidget(batt_display_1);
        splitter_1 = new QSplitter(container_RSU_1);
        splitter_1->setObjectName(QString::fromUtf8("splitter_1"));
        splitter_1->setOrientation(Qt::Horizontal);
        temp_pb_1 = new QProgressBar(splitter_1);
        temp_pb_1->setObjectName(QString::fromUtf8("temp_pb_1"));
        temp_pb_1->setEnabled(false);
        temp_pb_1->setMinimum(-10);
        temp_pb_1->setMaximum(40);
        temp_pb_1->setValue(-10);
        temp_pb_1->setTextVisible(false);
        temp_pb_1->setOrientation(Qt::Vertical);
        temp_pb_1->setInvertedAppearance(false);
        splitter_1->addWidget(temp_pb_1);
        batt_pb_1 = new QProgressBar(splitter_1);
        batt_pb_1->setObjectName(QString::fromUtf8("batt_pb_1"));
        batt_pb_1->setEnabled(false);
        batt_pb_1->setMaximum(5);
        batt_pb_1->setValue(0);
        batt_pb_1->setTextVisible(false);
        batt_pb_1->setOrientation(Qt::Vertical);
        batt_pb_1->setInvertedAppearance(false);
        splitter_1->addWidget(batt_pb_1);
        container_RSU_1->addWidget(splitter_1);
        splitter->addWidget(container_RSU_1);
        container_RSU_2 = new QSplitter(splitter);
        container_RSU_2->setObjectName(QString::fromUtf8("container_RSU_2"));
        container_RSU_2->setOrientation(Qt::Vertical);
        label_RSU_2 = new QLabel(container_RSU_2);
        label_RSU_2->setObjectName(QString::fromUtf8("label_RSU_2"));
        label_RSU_2->setFont(font2);
        label_RSU_2->setAlignment(Qt::AlignCenter);
        label_RSU_2->setWordWrap(false);
        container_RSU_2->addWidget(label_RSU_2);
        temp_display_2 = new QLCDNumber(container_RSU_2);
        temp_display_2->setObjectName(QString::fromUtf8("temp_display_2"));
        temp_display_2->setEnabled(false);
        temp_display_2->setFrameShape(QFrame::Box);
        temp_display_2->setFrameShadow(QFrame::Plain);
        temp_display_2->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_2->addWidget(temp_display_2);
        batt_display_2 = new QLCDNumber(container_RSU_2);
        batt_display_2->setObjectName(QString::fromUtf8("batt_display_2"));
        batt_display_2->setEnabled(false);
        batt_display_2->setFrameShape(QFrame::Box);
        batt_display_2->setFrameShadow(QFrame::Plain);
        batt_display_2->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_2->addWidget(batt_display_2);
        splitter_2 = new QSplitter(container_RSU_2);
        splitter_2->setObjectName(QString::fromUtf8("splitter_2"));
        splitter_2->setOrientation(Qt::Horizontal);
        temp_pb_2 = new QProgressBar(splitter_2);
        temp_pb_2->setObjectName(QString::fromUtf8("temp_pb_2"));
        temp_pb_2->setEnabled(false);
        temp_pb_2->setMinimum(-10);
        temp_pb_2->setMaximum(40);
        temp_pb_2->setValue(-10);
        temp_pb_2->setTextVisible(false);
        temp_pb_2->setOrientation(Qt::Vertical);
        temp_pb_2->setInvertedAppearance(false);
        splitter_2->addWidget(temp_pb_2);
        batt_pb_2 = new QProgressBar(splitter_2);
        batt_pb_2->setObjectName(QString::fromUtf8("batt_pb_2"));
        batt_pb_2->setEnabled(false);
        batt_pb_2->setMaximum(5);
        batt_pb_2->setValue(0);
        batt_pb_2->setTextVisible(false);
        batt_pb_2->setOrientation(Qt::Vertical);
        batt_pb_2->setInvertedAppearance(false);
        splitter_2->addWidget(batt_pb_2);
        container_RSU_2->addWidget(splitter_2);
        splitter->addWidget(container_RSU_2);
        container_RSU_3 = new QSplitter(splitter);
        container_RSU_3->setObjectName(QString::fromUtf8("container_RSU_3"));
        container_RSU_3->setOrientation(Qt::Vertical);
        label_RSU_3 = new QLabel(container_RSU_3);
        label_RSU_3->setObjectName(QString::fromUtf8("label_RSU_3"));
        label_RSU_3->setFont(font2);
        label_RSU_3->setAlignment(Qt::AlignCenter);
        label_RSU_3->setWordWrap(false);
        container_RSU_3->addWidget(label_RSU_3);
        temp_display_3 = new QLCDNumber(container_RSU_3);
        temp_display_3->setObjectName(QString::fromUtf8("temp_display_3"));
        temp_display_3->setEnabled(false);
        temp_display_3->setFrameShape(QFrame::Box);
        temp_display_3->setFrameShadow(QFrame::Plain);
        temp_display_3->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_3->addWidget(temp_display_3);
        batt_display_3 = new QLCDNumber(container_RSU_3);
        batt_display_3->setObjectName(QString::fromUtf8("batt_display_3"));
        batt_display_3->setEnabled(false);
        batt_display_3->setFrameShape(QFrame::Box);
        batt_display_3->setFrameShadow(QFrame::Plain);
        batt_display_3->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_3->addWidget(batt_display_3);
        splitter_3 = new QSplitter(container_RSU_3);
        splitter_3->setObjectName(QString::fromUtf8("splitter_3"));
        splitter_3->setOrientation(Qt::Horizontal);
        temp_pb_3 = new QProgressBar(splitter_3);
        temp_pb_3->setObjectName(QString::fromUtf8("temp_pb_3"));
        temp_pb_3->setEnabled(false);
        temp_pb_3->setMinimum(-10);
        temp_pb_3->setMaximum(40);
        temp_pb_3->setValue(-10);
        temp_pb_3->setTextVisible(false);
        temp_pb_3->setOrientation(Qt::Vertical);
        temp_pb_3->setInvertedAppearance(false);
        splitter_3->addWidget(temp_pb_3);
        batt_pb_3 = new QProgressBar(splitter_3);
        batt_pb_3->setObjectName(QString::fromUtf8("batt_pb_3"));
        batt_pb_3->setEnabled(false);
        batt_pb_3->setMaximum(5);
        batt_pb_3->setValue(0);
        batt_pb_3->setTextVisible(false);
        batt_pb_3->setOrientation(Qt::Vertical);
        batt_pb_3->setInvertedAppearance(false);
        splitter_3->addWidget(batt_pb_3);
        container_RSU_3->addWidget(splitter_3);
        splitter->addWidget(container_RSU_3);
        container_RSU_4 = new QSplitter(splitter);
        container_RSU_4->setObjectName(QString::fromUtf8("container_RSU_4"));
        container_RSU_4->setOrientation(Qt::Vertical);
        label_RSU_4 = new QLabel(container_RSU_4);
        label_RSU_4->setObjectName(QString::fromUtf8("label_RSU_4"));
        label_RSU_4->setFont(font2);
        label_RSU_4->setAlignment(Qt::AlignCenter);
        label_RSU_4->setWordWrap(false);
        container_RSU_4->addWidget(label_RSU_4);
        temp_display_4 = new QLCDNumber(container_RSU_4);
        temp_display_4->setObjectName(QString::fromUtf8("temp_display_4"));
        temp_display_4->setEnabled(false);
        temp_display_4->setFrameShape(QFrame::Box);
        temp_display_4->setFrameShadow(QFrame::Plain);
        temp_display_4->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_4->addWidget(temp_display_4);
        batt_display_4 = new QLCDNumber(container_RSU_4);
        batt_display_4->setObjectName(QString::fromUtf8("batt_display_4"));
        batt_display_4->setEnabled(false);
        batt_display_4->setFrameShape(QFrame::Box);
        batt_display_4->setFrameShadow(QFrame::Plain);
        batt_display_4->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_4->addWidget(batt_display_4);
        splitter_4 = new QSplitter(container_RSU_4);
        splitter_4->setObjectName(QString::fromUtf8("splitter_4"));
        splitter_4->setOrientation(Qt::Horizontal);
        temp_pb_4 = new QProgressBar(splitter_4);
        temp_pb_4->setObjectName(QString::fromUtf8("temp_pb_4"));
        temp_pb_4->setEnabled(false);
        temp_pb_4->setMinimum(-10);
        temp_pb_4->setMaximum(40);
        temp_pb_4->setValue(-10);
        temp_pb_4->setTextVisible(false);
        temp_pb_4->setOrientation(Qt::Vertical);
        temp_pb_4->setInvertedAppearance(false);
        splitter_4->addWidget(temp_pb_4);
        batt_pb_4 = new QProgressBar(splitter_4);
        batt_pb_4->setObjectName(QString::fromUtf8("batt_pb_4"));
        batt_pb_4->setEnabled(false);
        batt_pb_4->setMaximum(5);
        batt_pb_4->setValue(0);
        batt_pb_4->setTextVisible(false);
        batt_pb_4->setOrientation(Qt::Vertical);
        batt_pb_4->setInvertedAppearance(false);
        splitter_4->addWidget(batt_pb_4);
        container_RSU_4->addWidget(splitter_4);
        splitter->addWidget(container_RSU_4);
        container_RSU_5 = new QSplitter(splitter);
        container_RSU_5->setObjectName(QString::fromUtf8("container_RSU_5"));
        container_RSU_5->setOrientation(Qt::Vertical);
        label_RSU_5 = new QLabel(container_RSU_5);
        label_RSU_5->setObjectName(QString::fromUtf8("label_RSU_5"));
        label_RSU_5->setFont(font2);
        label_RSU_5->setAlignment(Qt::AlignCenter);
        label_RSU_5->setWordWrap(false);
        container_RSU_5->addWidget(label_RSU_5);
        temp_display_5 = new QLCDNumber(container_RSU_5);
        temp_display_5->setObjectName(QString::fromUtf8("temp_display_5"));
        temp_display_5->setEnabled(false);
        temp_display_5->setFrameShape(QFrame::Box);
        temp_display_5->setFrameShadow(QFrame::Plain);
        temp_display_5->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_5->addWidget(temp_display_5);
        batt_display_5 = new QLCDNumber(container_RSU_5);
        batt_display_5->setObjectName(QString::fromUtf8("batt_display_5"));
        batt_display_5->setEnabled(false);
        batt_display_5->setFrameShape(QFrame::Box);
        batt_display_5->setFrameShadow(QFrame::Plain);
        batt_display_5->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_5->addWidget(batt_display_5);
        splitter_5 = new QSplitter(container_RSU_5);
        splitter_5->setObjectName(QString::fromUtf8("splitter_5"));
        splitter_5->setOrientation(Qt::Horizontal);
        temp_pb_5 = new QProgressBar(splitter_5);
        temp_pb_5->setObjectName(QString::fromUtf8("temp_pb_5"));
        temp_pb_5->setEnabled(false);
        temp_pb_5->setMinimum(-10);
        temp_pb_5->setMaximum(40);
        temp_pb_5->setValue(-10);
        temp_pb_5->setTextVisible(false);
        temp_pb_5->setOrientation(Qt::Vertical);
        temp_pb_5->setInvertedAppearance(false);
        splitter_5->addWidget(temp_pb_5);
        batt_pb_5 = new QProgressBar(splitter_5);
        batt_pb_5->setObjectName(QString::fromUtf8("batt_pb_5"));
        batt_pb_5->setEnabled(false);
        batt_pb_5->setMaximum(5);
        batt_pb_5->setValue(0);
        batt_pb_5->setTextVisible(false);
        batt_pb_5->setOrientation(Qt::Vertical);
        batt_pb_5->setInvertedAppearance(false);
        splitter_5->addWidget(batt_pb_5);
        container_RSU_5->addWidget(splitter_5);
        splitter->addWidget(container_RSU_5);
        container_RSU_6 = new QSplitter(splitter);
        container_RSU_6->setObjectName(QString::fromUtf8("container_RSU_6"));
        container_RSU_6->setOrientation(Qt::Vertical);
        label_RSU_6 = new QLabel(container_RSU_6);
        label_RSU_6->setObjectName(QString::fromUtf8("label_RSU_6"));
        label_RSU_6->setFont(font2);
        label_RSU_6->setAlignment(Qt::AlignCenter);
        label_RSU_6->setWordWrap(false);
        container_RSU_6->addWidget(label_RSU_6);
        temp_display_6 = new QLCDNumber(container_RSU_6);
        temp_display_6->setObjectName(QString::fromUtf8("temp_display_6"));
        temp_display_6->setEnabled(false);
        temp_display_6->setFrameShape(QFrame::Box);
        temp_display_6->setFrameShadow(QFrame::Plain);
        temp_display_6->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_6->addWidget(temp_display_6);
        batt_display_6 = new QLCDNumber(container_RSU_6);
        batt_display_6->setObjectName(QString::fromUtf8("batt_display_6"));
        batt_display_6->setEnabled(false);
        batt_display_6->setFrameShape(QFrame::Box);
        batt_display_6->setFrameShadow(QFrame::Plain);
        batt_display_6->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_6->addWidget(batt_display_6);
        splitter_6 = new QSplitter(container_RSU_6);
        splitter_6->setObjectName(QString::fromUtf8("splitter_6"));
        splitter_6->setOrientation(Qt::Horizontal);
        temp_pb_6 = new QProgressBar(splitter_6);
        temp_pb_6->setObjectName(QString::fromUtf8("temp_pb_6"));
        temp_pb_6->setEnabled(false);
        temp_pb_6->setMinimum(-10);
        temp_pb_6->setMaximum(40);
        temp_pb_6->setValue(-10);
        temp_pb_6->setTextVisible(false);
        temp_pb_6->setOrientation(Qt::Vertical);
        temp_pb_6->setInvertedAppearance(false);
        splitter_6->addWidget(temp_pb_6);
        batt_pb_6 = new QProgressBar(splitter_6);
        batt_pb_6->setObjectName(QString::fromUtf8("batt_pb_6"));
        batt_pb_6->setEnabled(false);
        batt_pb_6->setMaximum(5);
        batt_pb_6->setValue(0);
        batt_pb_6->setTextVisible(false);
        batt_pb_6->setOrientation(Qt::Vertical);
        batt_pb_6->setInvertedAppearance(false);
        splitter_6->addWidget(batt_pb_6);
        container_RSU_6->addWidget(splitter_6);
        splitter->addWidget(container_RSU_6);
        container_RSU_7 = new QSplitter(splitter);
        container_RSU_7->setObjectName(QString::fromUtf8("container_RSU_7"));
        container_RSU_7->setOrientation(Qt::Vertical);
        label_RSU_7 = new QLabel(container_RSU_7);
        label_RSU_7->setObjectName(QString::fromUtf8("label_RSU_7"));
        label_RSU_7->setFont(font2);
        label_RSU_7->setAlignment(Qt::AlignCenter);
        label_RSU_7->setWordWrap(false);
        container_RSU_7->addWidget(label_RSU_7);
        temp_display_7 = new QLCDNumber(container_RSU_7);
        temp_display_7->setObjectName(QString::fromUtf8("temp_display_7"));
        temp_display_7->setEnabled(false);
        temp_display_7->setFrameShape(QFrame::Box);
        temp_display_7->setFrameShadow(QFrame::Plain);
        temp_display_7->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_7->addWidget(temp_display_7);
        batt_display_7 = new QLCDNumber(container_RSU_7);
        batt_display_7->setObjectName(QString::fromUtf8("batt_display_7"));
        batt_display_7->setEnabled(false);
        batt_display_7->setFrameShape(QFrame::Box);
        batt_display_7->setFrameShadow(QFrame::Plain);
        batt_display_7->setSegmentStyle(QLCDNumber::Flat);
        container_RSU_7->addWidget(batt_display_7);
        splitter_7 = new QSplitter(container_RSU_7);
        splitter_7->setObjectName(QString::fromUtf8("splitter_7"));
        splitter_7->setOrientation(Qt::Horizontal);
        temp_pb_7 = new QProgressBar(splitter_7);
        temp_pb_7->setObjectName(QString::fromUtf8("temp_pb_7"));
        temp_pb_7->setEnabled(false);
        temp_pb_7->setMinimum(-10);
        temp_pb_7->setMaximum(40);
        temp_pb_7->setValue(-10);
        temp_pb_7->setTextVisible(false);
        temp_pb_7->setOrientation(Qt::Vertical);
        temp_pb_7->setInvertedAppearance(false);
        splitter_7->addWidget(temp_pb_7);
        batt_pb_7 = new QProgressBar(splitter_7);
        batt_pb_7->setObjectName(QString::fromUtf8("batt_pb_7"));
        batt_pb_7->setEnabled(false);
        batt_pb_7->setMaximum(5);
        batt_pb_7->setValue(0);
        batt_pb_7->setTextVisible(false);
        batt_pb_7->setOrientation(Qt::Vertical);
        batt_pb_7->setInvertedAppearance(false);
        splitter_7->addWidget(batt_pb_7);
        container_RSU_7->addWidget(splitter_7);
        splitter->addWidget(container_RSU_7);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(90, 590, 67, 17));
        QFont font3;
        font3.setBold(true);
        font3.setUnderline(true);
        font3.setWeight(75);
        label_3->setFont(font3);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(60, 610, 101, 21));
        label_4->setFont(font3);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(40, 637, 121, 21));
        label_5->setFont(font3);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(680, 610, 51, 21));
        label_6->setFont(font3);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(680, 637, 51, 21));
        label_7->setFont(font3);
        MU_message_cb = new QComboBox(centralWidget);
        MU_message_cb->addItem(QString());
        MU_message_cb->addItem(QString());
        MU_message_cb->addItem(QString());
        MU_message_cb->addItem(QString());
        MU_message_cb->addItem(QString());
        MU_message_cb->addItem(QString());
        MU_message_cb->setObjectName(QString::fromUtf8("MU_message_cb"));
        MU_message_cb->setEnabled(false);
        MU_message_cb->setGeometry(QRect(400, 210, 161, 31));
        serial_MUsend_button = new QPushButton(centralWidget);
        serial_MUsend_button->setObjectName(QString::fromUtf8("serial_MUsend_button"));
        serial_MUsend_button->setEnabled(false);
        serial_MUsend_button->setGeometry(QRect(400, 245, 161, 31));
        QFont font4;
        font4.setPointSize(11);
        font4.setBold(false);
        font4.setWeight(50);
        serial_MUsend_button->setFont(font4);
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(420, 180, 131, 28));
        label_9->setFont(font2);
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(410, 279, 131, 28));
        label_10->setFont(font2);
        label_10->setAlignment(Qt::AlignCenter);
        MU_message_response_lb = new QLabel(centralWidget);
        MU_message_response_lb->setObjectName(QString::fromUtf8("MU_message_response_lb"));
        MU_message_response_lb->setGeometry(QRect(400, 310, 151, 28));
        MU_message_response_lb->setFont(font2);
        MU_message_response_lb->setAlignment(Qt::AlignCenter);
        splitter_8 = new QSplitter(centralWidget);
        splitter_8->setObjectName(QString::fromUtf8("splitter_8"));
        splitter_8->setGeometry(QRect(800, 590, 131, 151));
        splitter_8->setOrientation(Qt::Vertical);
        label_8 = new QLabel(splitter_8);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setFont(font2);
        label_8->setAlignment(Qt::AlignCenter);
        splitter_8->addWidget(label_8);
        power_cb = new QComboBox(splitter_8);
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->addItem(QString());
        power_cb->setObjectName(QString::fromUtf8("power_cb"));
        splitter_8->addWidget(power_cb);
        power_button = new QPushButton(splitter_8);
        power_button->setObjectName(QString::fromUtf8("power_button"));
        power_button->setEnabled(false);
        power_button->setFont(font4);
        splitter_8->addWidget(power_button);
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 374, 181, 28));
        label_11->setFont(font2);
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(680, 732, 21, 17));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(680, 662, 21, 17));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(120, 730, 31, 20));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(120, 662, 31, 20));
        sector_RSU_sp_1 = new QSpinBox(centralWidget);
        sector_RSU_sp_1->setObjectName(QString::fromUtf8("sector_RSU_sp_1"));
        sector_RSU_sp_1->setGeometry(QRect(154, 540, 31, 26));
        sector_RSU_sp_1->setMaximum(8);
        sector_RSU_sp_2 = new QSpinBox(centralWidget);
        sector_RSU_sp_2->setObjectName(QString::fromUtf8("sector_RSU_sp_2"));
        sector_RSU_sp_2->setGeometry(QRect(280, 540, 31, 26));
        sector_RSU_sp_2->setMaximum(8);
        sector_RSU_sp_3 = new QSpinBox(centralWidget);
        sector_RSU_sp_3->setObjectName(QString::fromUtf8("sector_RSU_sp_3"));
        sector_RSU_sp_3->setGeometry(QRect(406, 540, 31, 26));
        sector_RSU_sp_3->setMaximum(8);
        sector_RSU_sp_4 = new QSpinBox(centralWidget);
        sector_RSU_sp_4->setObjectName(QString::fromUtf8("sector_RSU_sp_4"));
        sector_RSU_sp_4->setGeometry(QRect(530, 540, 31, 26));
        sector_RSU_sp_4->setMaximum(8);
        sector_RSU_sp_5 = new QSpinBox(centralWidget);
        sector_RSU_sp_5->setObjectName(QString::fromUtf8("sector_RSU_sp_5"));
        sector_RSU_sp_5->setGeometry(QRect(656, 540, 31, 26));
        sector_RSU_sp_5->setMaximum(8);
        sector_RSU_sp_6 = new QSpinBox(centralWidget);
        sector_RSU_sp_6->setObjectName(QString::fromUtf8("sector_RSU_sp_6"));
        sector_RSU_sp_6->setGeometry(QRect(780, 540, 31, 26));
        sector_RSU_sp_6->setMaximum(8);
        sector_RSU_sp_7 = new QSpinBox(centralWidget);
        sector_RSU_sp_7->setObjectName(QString::fromUtf8("sector_RSU_sp_7"));
        sector_RSU_sp_7->setGeometry(QRect(907, 540, 31, 26));
        sector_RSU_sp_7->setMaximum(8);
        sector_RSU_sp_8 = new QSpinBox(centralWidget);
        sector_RSU_sp_8->setObjectName(QString::fromUtf8("sector_RSU_sp_8"));
        sector_RSU_sp_8->setGeometry(QRect(1032, 540, 31, 26));
        sector_RSU_sp_8->setMaximum(8);
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(201, 541, 61, 21));
        QFont font5;
        font5.setBold(true);
        font5.setItalic(true);
        font5.setUnderline(false);
        font5.setWeight(75);
        label_16->setFont(font5);
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(330, 540, 61, 21));
        label_17->setFont(font5);
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(954, 540, 61, 21));
        label_18->setFont(font5);
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(455, 540, 61, 21));
        label_19->setFont(font5);
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(829, 540, 61, 21));
        label_20->setFont(font5);
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(704, 540, 61, 21));
        label_21->setFont(font5);
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(581, 540, 61, 21));
        label_22->setFont(font5);
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QApplication::translate("MainWindow", "Port:", nullptr));
        status->setText(QApplication::translate("MainWindow", "Status Messages", nullptr));
        test_button->setText(QApplication::translate("MainWindow", "DEBUG", nullptr));
        test_button_2->setText(QApplication::translate("MainWindow", "DEBUG_2", nullptr));
        serial_search_button->setText(QApplication::translate("MainWindow", "Search", nullptr));
        serial_open_button->setText(QApplication::translate("MainWindow", "Open", nullptr));
        serial_close_button->setText(QApplication::translate("MainWindow", "Close", nullptr));
        serial_clear_output_button->setText(QApplication::translate("MainWindow", "Clear", nullptr));
        count_reset_button->setText(QApplication::translate("MainWindow", "Count Reset", nullptr));
        reorder_button->setText(QApplication::translate("MainWindow", "Reorder", nullptr));
        serial_send_button->setText(QApplication::translate("MainWindow", "SEND", nullptr));
        clear_warning_button->setText(QApplication::translate("MainWindow", "Warning OK", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Warning Messages:", nullptr));
        test_button_3->setText(QApplication::translate("MainWindow", "DEBUG_3", nullptr));
        label_RSU_1->setText(QApplication::translate("MainWindow", "RSU2", nullptr));
        label_RSU_2->setText(QApplication::translate("MainWindow", "RSU3", nullptr));
        label_RSU_3->setText(QApplication::translate("MainWindow", "RSU4", nullptr));
        label_RSU_4->setText(QApplication::translate("MainWindow", "RSU5", nullptr));
        label_RSU_5->setText(QApplication::translate("MainWindow", "RSU6", nullptr));
        label_RSU_6->setText(QApplication::translate("MainWindow", "RSU7", nullptr));
        label_RSU_7->setText(QApplication::translate("MainWindow", "RSU8", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Mote ID", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Temperature", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Battery Voltage", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "0-40 C", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "0-5 V", nullptr));
        MU_message_cb->setItemText(0, QApplication::translate("MainWindow", "Send location!", nullptr));
        MU_message_cb->setItemText(1, QApplication::translate("MainWindow", "Are you OK?", nullptr));
        MU_message_cb->setItemText(2, QApplication::translate("MainWindow", "How many people?", nullptr));
        MU_message_cb->setItemText(3, QApplication::translate("MainWindow", "Help on way!", nullptr));
        MU_message_cb->setItemText(4, QApplication::translate("MainWindow", "Is there fire?", nullptr));
        MU_message_cb->setItemText(5, QApplication::translate("MainWindow", "Firetruck on way!", nullptr));

        serial_MUsend_button->setText(QApplication::translate("MainWindow", "Send Message", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Send to MU!", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "MU_Response", nullptr));
        MU_message_response_lb->setText(QApplication::translate("MainWindow", "...", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Set TX Power:", nullptr));
        power_cb->setItemText(0, QApplication::translate("MainWindow", "+7 dBm", nullptr));
        power_cb->setItemText(1, QApplication::translate("MainWindow", "+5 dBm", nullptr));
        power_cb->setItemText(2, QApplication::translate("MainWindow", "+3 dBm", nullptr));
        power_cb->setItemText(3, QApplication::translate("MainWindow", "+1 dBm", nullptr));
        power_cb->setItemText(4, QApplication::translate("MainWindow", "0 dBm", nullptr));
        power_cb->setItemText(5, QApplication::translate("MainWindow", "-1 dBm", nullptr));
        power_cb->setItemText(6, QApplication::translate("MainWindow", "-3 dBm", nullptr));
        power_cb->setItemText(7, QApplication::translate("MainWindow", "-5 dBm", nullptr));
        power_cb->setItemText(8, QApplication::translate("MainWindow", "-7 dBm", nullptr));
        power_cb->setItemText(9, QApplication::translate("MainWindow", "-9 dBm", nullptr));
        power_cb->setItemText(10, QApplication::translate("MainWindow", "-11 dBm", nullptr));
        power_cb->setItemText(11, QApplication::translate("MainWindow", "-13 dBm", nullptr));
        power_cb->setItemText(12, QApplication::translate("MainWindow", "-15 dBm", nullptr));
        power_cb->setItemText(13, QApplication::translate("MainWindow", "-24 dBm", nullptr));

        power_button->setText(QApplication::translate("MainWindow", "Broadcast Tx Pwr", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Custom serial command", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "0V", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "5V", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "-10C", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "40C", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Sector 1", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Sector 2", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Sector 7", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "Sector 3", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Sector 6", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Sector 5", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Sector 4", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
